name: homepage - CI

on: pull_request

jobs:
  test-pug:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - run: npm install
      - name: Run Pug compiler
        run: npm run pug

  test-sass:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - run: npm install
      - name: Run SASS compiler
        run: npm run scss
