name: Master build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '11.*'
      - run: npm install
      - name: Build homepage
        run: npm run build
      - name: Deploy build
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PATH: ${{ secrets.PATH }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          echo "${SSH_KEY}" > id_github.key
          /bin/chmod 600 id_github.key
          /usr/bin/rsync \
            --archive --verbose --compress --recursive \
            --rsh="/usr/bin/ssh -p ${SSH_PORT} -i id_github.key" \
            build "${USER}@${HOST}:${PATH}"
          rm id_github.key
