name: Master build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # This action breaks $PATH, so install node manually
      #- uses: actions/setup-node@v2.1.4
      #  with:
      #    node-version: '14'
      - name: Setup node
        run: sudo apt install --yes nodejs npm
      - name: Install project packages
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy build
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PATH: ${{ secrets.PATH }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          echo "${SSH_KEY}" > id_github
          /bin/chmod 600 id_github
          /usr/bin/rsync \
            --archive --verbose --compress --recursive --delete-after \
            --rsh="/usr/bin/ssh -p ${SSH_PORT} -i id_github -o StrictHostKeyChecking=no" \
            build/* "${USER}@${HOST}:${PATH}"
          /bin/rm id_github
